name: fcharts_example
description: Demonstrates how to use the fcharts plugin.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  fcharts:
    path: ../
flutter:
  uses-material-design: true