name: fcharts
description: A Flutter chart library.
version: 0.0.2
author: Keenan Thompson <keenan@keenant.com>
homepage: https://github.com/thekeenant/fcharts

dependencies:
  flutter:
    sdk: flutter
  meta: "^1.1.2"
  collection: "^1.14.6"

environment:
  sdk: ">=1.19.0 <2.0.0"
  flutter: "^0.2.1"
