name: fcharts
description: A Flutter chart library.
version: 0.0.1
author: Keenan Thompson
homepage: https://github.com/thekeenant/fcharts

dependencies:
  flutter:
    sdk: flutter
  quiver: ">=0.28.0 <0.29.0"
